// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9YX358lFr8Fb4mBSqkPueVnMDgDuBaBo',
    appId: '1:965792184735:web:708dea9c63d550ebc525aa',
    messagingSenderId: '965792184735',
    projectId: 'mitra-e870d',
    authDomain: 'mitra-e870d.firebaseapp.com',
    storageBucket: 'mitra-e870d.firebasestorage.app',
    measurementId: 'G-G7GC5C3TQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ5BGvEZyljLa5Sl_OdzwqYW5j1KRPnBg',
    appId: '1:965792184735:android:e9f924a3b8f2d80dc525aa',
    messagingSenderId: '965792184735',
    projectId: 'mitra-e870d',
    storageBucket: 'mitra-e870d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDtkgHGHWOFAIbSjKNxx59IELC2sDaGg',
    appId: '1:965792184735:ios:86decf23ccd713cfc525aa',
    messagingSenderId: '965792184735',
    projectId: 'mitra-e870d',
    storageBucket: 'mitra-e870d.firebasestorage.app',
    iosBundleId: 'com.example.mitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRDtkgHGHWOFAIbSjKNxx59IELC2sDaGg',
    appId: '1:965792184735:ios:86decf23ccd713cfc525aa',
    messagingSenderId: '965792184735',
    projectId: 'mitra-e870d',
    storageBucket: 'mitra-e870d.firebasestorage.app',
    iosBundleId: 'com.example.mitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtfedYp_XftFxwqtVigWILlC1I--Zigvo',
    appId: '1:965792184735:web:6b1e0cb0aabc31a8c525aa',
    messagingSenderId: '965792184735',
    projectId: 'mitra-e870d',
    authDomain: 'mitra-e870d.firebaseapp.com',
    storageBucket: 'mitra-e870d.firebasestorage.app',
    measurementId: 'G-HJ9YQSZ0J2',
  );
}
